### ISSUE TITLE
Version Update For React 17.0.2 and above

### ISSUE THREAD

**Issue by abelchua** [vtaits/react-color-picker#1]
Hello! 

Will there be any version updates for compatibility for React 17.0.2 and above? 

Regards,
Abel

**Comment by vtaits** [comment]
Hello. I forgot about this library :smile:  Ok, i'll upgrade dependencies.

**Comment by abelchua** [comment]
Awesome thanks!

**Comment by vtaits** [comment]
Version `0.1.2`.
